{% set name = "gridmap" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gridmap-{{ version }}.tar.gz
  sha256: 5cb1634e1400ba5fa6708b4c94c09a1772c8300951faa76556d2a69579eba6f0

build:
  number: 1
  noarch: python
  entry_points:
    - gridmap_web = gridmap.web:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cloudpickle
    - drmaa
    - psutil >=2.0.0
    - python >={{ python_min }}
    - pyzmq
    - matplotlib-base
    - cherrypy

test:
  imports:
    - gridmap
  commands:
    - pip check
    - gridmap_web --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/EducationalTestingService/gridmap
  summary: Easily map Python functions onto a cluster using a DRMAA-compatible grid engine like Sun Grid Engine (SGE).
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dpryan79
